'use client';

import {
  AlertCircle,
  Loader2,
  RefreshCw,
  CheckCircle,
  XCircle,
  ChevronRight,
  ChevronLeft,
  Plus,
  Trash,
  Edit,
  Settings,
  LogOut,
  User,
  Home,
  BookOpen,
  Video,
  FileText,
  Mail,
  Calendar,
  MoreHorizontal,
  Search,
} from 'lucide-react';

// Export all Lucide icons as an object for easy consumption
export const Icons = {
  alertCircle: AlertCircle,
  loader2: Loader2,
  refresh: RefreshCw,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  plus: Plus,
  trash: Trash,
  edit: Edit,
  settings: Settings,
  logout: LogOut,
  user: User,
  home: Home,
  bookOpen: BookOpen,
  video: Video,
  fileText: FileText,
  mail: Mail,
  calendar: Calendar,
  moreHorizontal: MoreHorizontal,
  search: Search,
}; 